name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean package -DskipTests
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
        
      -  
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        with:
          name: Package
          path: staging
    
      - name: Display structure of downloaded files
        run: ls -R    

  deploy:
    runs-on: ubuntu-18.04
    needs: build
    
    steps:
    
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          name: Package
          path: staging
    
      - name: Display structure of downloaded files
        run: ls -R
        
      - name: Docker build
        run: |
          docker build . -t dehghan68/nab-app:0.0.2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker push
        run: |
          docker push dehghan68/nab-app:0.0.2
          
          
      - name: Deploy to Liara    
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: update-liara
        env:
          LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
        run: |
          npm i -g @liara/cli@3.0.1
          liara deploy --app="nab" --api-token="$LIARA_TOKEN" -p=80 --detach    
          
