name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean install -DskipTests
      - name: Publish to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: dehghan68/nab-app
          tags: 0.0.1 
     # - name: Build the Docker image
     # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
     # - name: Set up JDK
     # uses: actions/setup-java@v1
     # with:
     #   java-version: 1.11
    #- name: Build with Maven
     # run: mvn clean install
    #- name: Publish to Docker Hub
    #  uses: docker/build-push-action@v1
     # with:
      # username: ${{ secrets.DOCKER_HUB_USERNAME }}
      # password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      # repository: dockerHubUser/dockerHubRepository
      # tags: ${{github.run_number}} 
  #build:
  #runs-on: ubuntu-latest
   # steps:
   # - uses: actions/checkout@v2
    #- name: Set up JDK
    #  uses: actions/setup-java@v1
     # with:
     #   java-version: 1.11
   # - name: Build with Maven
    #  run: mvn clean install
    #- name: Publish to Docker Hub
    #  uses: docker/build-push-action@v1
     # with:
     #  username: ${{ secrets.DOCKER_HUB_USERNAME }}
      # password: ${{ secrets.DOCKER_HUB_PASSWORD }}
       #repository: dockerHubUser/dockerHubRepository
       #tags: ${{github.run_number}}   
